### ISSUE TITLE
Input format?

### ISSUE THREAD

**Issue by arne-cl** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#1]
Dear Aaqib,

could you provide an example for the `data.csv` file used in the notebook?

Best regards,
Arne

**Comment by aqibsaeed** [comment]
Data can be any time series sequence, as in the paper it is electronic health records (EHR) of patients with multiple diagnosis as class labels. The EHR data set is not publicly available, for it's format/description please see paper.
