### ISSUE TITLE
Clarification regarding the data shape illustration

### ISSUE THREAD

**Issue by BY-hash** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#10]
Hello,
Regarding the illustration of the shape of the data:
"Each training example will be a sequence of shape [1, time_steps, number_of_features]"
However, in the code:
"segments=segments.reshape([len(segments),(win_size + 1),1])"
If I understand correctly, win_size = number_of_features + 1 (because an extra feature of the tims step) and len(segments)=time_steps
So it seems there is a mismatch between the order of dimensions in the illustration and the code

Could you please clearify this issue?
Thank you!

**Comment by aqibsaeed** [comment]
Hi,

`[1, time_steps, number_of_features]` is correct, where `1` or first dimension represents the batch size or total number of examples. In `segments` if I remember correctly there was only one feature for each timestep. `len(segments)` are the total number of examples, which in your example is `1`.  For example, for an accelerometer signal, we can generate training examples with time steps = 500, number of features = 3 (i.e., 3-axes of accelerometer signal) and the first dimension will simply represent total number of examples. Hope this helps.
