### ISSUE TITLE
data.csv missing

### ISSUE THREAD

**Issue by pannous** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#2]

**Comment by aqibsaeed** [comment]
Electronic health records data of patients are not publicly available because of sensitive information. For the data set format/description please see the paper.

**Comment by pannous** [comment]
some example data would be really helpful.
 otherwise all of the thousand users who are currently trying your code will run against a wall and have to somehow make up their data themselves. (100stars~1000users)

**Comment by aqibsaeed** [comment]
I am sorry for this, I completely understand your point. I always add data sets in my repository when they are publicly available. I put the code so people who have similar data set (as discussed in the paper) available can try out the model.

Here is similar dataset named [MIMIC-III](http://mimic.mit.edu/about/mimic/). But as mentioned in the notebook pre-processing is required according to the use case.

**Comment by aqibsaeed** [comment]
Some more information on data set format. I hope, it will help and clear things up. 
The data set will look something like the figure below. 

<img src="https://raw.githubusercontent.com/aqibsaeed/aqibsaeed.github.io/master/img/mrnn_data_format.PNG" />

TEMP, PH etc. are all features, each red point represents feature value at one time point. Diagnosis vector (one-hot encoded) not shown in the picture will be class labels.
Each training example will be a sequence of shape `[1, time_steps, number_of_features]` so your batch's shape will be `[batch_size, time_steps, number_of_features]`.

Please see section on Dataset Description in paper for more detail.
