### ISSUE TITLE
The format of the input data

### ISSUE THREAD

**Issue by PerryDong** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#3]
Can you offer the 'data.csv' used to train this model, as I want to know the format of the input data. Thank you!

**Comment by aqibsaeed** [comment]
The data set will look something like the figure below. 

<img src="https://raw.githubusercontent.com/aqibsaeed/aqibsaeed.github.io/master/img/mrnn_data_format.PNG" />

TEMP, PH etc. are all features, each red point represents feature value at one time point. Diagnosis vector (one-hot encoded) not shown in the picture will be class labels.
Each training example will be a sequence of shape `[1, time_steps, number_of_features]` so your batch's shape will be `[batch_size, time_steps, number_of_features]`.

Please see section on Dataset Description in paper for more detail. You can use subset of MIMIC-III. But as mentioned in the notebook pre-processing is required according to the use case.
