### ISSUE TITLE
multilabel classification ?

### ISSUE THREAD

**Issue by queyanaimao** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#7]
excuse me，the original is a multi-label classification problem, I did not get to know how your label is processed, after study your code I think your label is a single multi-label classification problem, am i wrong?
would you help me to explain the label question? very very thank you!!

**Comment by aqibsaeed** [comment]
Don't understand what do you mean by multi-label classification problem and single multi-label classification problem. For labels and dataset preparation see [ https://github.com/YerevaNN/mimic3-benchmarks](this).

**Comment by queyanaimao** [comment]
oh....I'm so sorry.I mean a sample has multiple labels, how to deal with the labels?

**Comment by aqibsaeed** [comment]
Check this:  https://github.com/YerevaNN/mimic3-benchmarks.
