### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by AnconaAndrea** [aqibsaeed/Multilabel-timeseries-classification-with-LSTM#9]
First of all, thank you for the code!

I know it has already been discussed, but it is not clear to me the data format in the csv file needed to run your code. Does it have to be two coloumns, first coloumn with the full time series and in the second coloum the label associated with each time step? or what else?

Thank you!

**Comment by aqibsaeed** [comment]
The data should be in the format below, considering X and Y to be numpy arrays: 
X: (batch_size, time_steps, n_features) and Y: (batch_size, n_classes)
For instance, assume you have triaxial accelerometer data and some classes in csv, then start  with segmenting it to have the same shape as above and perform one hot encoding to generate class labels. See [this post](https://aqibsaeed.github.io/2016-11-04-human-activity-recognition-cnn/), if you need help with pre-processing.
Hope this helps.
